/*
 * TIM_config.h
 *
 *  Created on: Aug 2, 2025
 *      Author: George Essmat
 */

#ifndef MCAL_TIM_TIM_CONFIG_H_
#define MCAL_TIM_TIM_CONFIG_H_

//Timer0 config
#define TIM0_u8_INITIAL_CLK			TIM0_u8_PRESCALER_8
#define TIM0_u8_INITIAL_MODE		TIM0_u8_NORMAL

#define TIM0_u8_INITIAL_PWM_CLK		TIM0_u8_PRESCALER_64
#define TIM0_u8_INTIIAL_PWM_MODE	TIM0_u8_FAST_PWM
//

//Timer1 config
#define TIM1_u8_INITIAL_CLK			TIM1_u8_PRESCALER_256
#define TIM1_u8_INITIAL_MODE		TIM1_u8_MODE_PWM_FAST_10_BIT

#define TIM1_u8_INITIAL_PWM_CLK		TIM1_u8_PRESCALER_256
#define TIM1_u8_INITIAL_PWM_MODE	TIM1_u8_MODE_PWM_FAST_10_BIT
//

//Timer2 config
#define TIM2_u8_INITIAL_CLK			TIM2_u8_NO_PRESCALER
#define TIM2_u8_INITIAL_MODE		TIM2_u8_NORMAL

#define TIM2_u8_INITIAL_PWM_CLK		TIM2_u8_PRESCALER_64
#define TIM2_u8_INTIIAL_PWM_MODE	TIM2_u8_FAST_PWM
//


#endif /* MCAL_TIM_TIM_CONFIG_H_ */
